### ISSUE TITLE
The author needs help

### ISSUE THREAD

**Issue by rainmanp7** [arunanshub/preload#2]
The author of the repository has a few errors in their code. One error is that they are trying to use the -Werror flag with the meson command. This flag will cause Meson to fail if there are any warnings, even if the warnings are not fatal. The author should remove the -Werror flag from their command.

Another error is that the author is trying to use the ninja build system to build their project. However, the ninja build system is not compatible with Meson. The author should use the meson build system to build their project.

**Comment by arunanshub** [comment]
@rainmanp7 
> However, the ninja build system is not compatible with Meson

In the Requirements section, it is mentioned that Ninja is a supported backend of Meson. However, `meson compile -C <builddir>` can also be used as a backend-agnostic alternative, even though using `ninja` does not hurt.

> One error is that they are trying to use the -Werror flag with the meson command. This flag will cause Meson to fail if there are any warnings, even if the warnings are not fatal. The author should remove the -Werror flag from their command.

Firstly, I'd like to see which part of the codebase fails to compile in the presence of `-Werror`.

**Comment by rainmanp7** [comment]
It works.
But only use the meson build.

Otherwise if people alter your code the person will think your stuff doesn't work , because of their own coding errors.

"fail if there are any warnings"

It's actually a good flag to put.
But you know how people are :-)

It's good to hear from you ,I really like what you have accomplished with it.

**Comment by arunanshub** [comment]
@rainmanp7 
> It works.
> But only use the meson build.
>
> Otherwise if people alter your code the person will think your stuff doesn't work , because of their own coding errors.

That's fair. Feel free to open a pull request.

> It's actually a good flag to put.
> But you know how people are :-)

I am not planning to remove `-Werror` flag just because people fail to notice errors or unsafe practices in their code. If it was rust, I'd have considered it, but you know how tricky C can be when it comes to bugs.

> It's good to hear from you ,I really like what you have accomplished with it.

Thank you for your kind words. It's actually Behdad Esfahbod's creation. I just upgraded and simplified some parts.

**Comment by arunanshub** [comment]
I just realised that there is nothing to remove since Meson handles it at build time.

https://github.com/mesonbuild/meson/issues/2427#issuecomment-334273742
